name: Publish Docker image

permissions:
  contents: write
  repository-projects: write
  packages: write

on:
  release:
    types: [published]

jobs:
  build_and_push:
    name: Push Docker image to Storequarters Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/storequarters/expose:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
